name: Java CI/CD

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
      #Récupère le code source à partir du référentiel.
      - name: Copy code to runner
        uses: actions/checkout@v3
      #Set up JDK : Installe la version 17 de JDK.
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      #Build with Maven : Nettoie le projet et exécute la construction avec Maven.
      - name: Build with Maven
        run: mvn clean install -e -X

      - name: Run unit tests
        run: mvn test

      - name: Run integration test
        run: mvn verify

      - name: Build Docker image
        run: docker build -t gestion-enseignants:v01 .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: aissatoudrame/gestion-enseignants:v01

  deploy:
    name: Déployer sur un VPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: S'assurer que le répertoire existe sur le VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: mkdir -p /docker-file-l3l2i

      - name: Transférer docker-compose sur le VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./docker-compose.yml"
          target: "/docker-file-l3l2i"

      - name: Déployer l'application sur le VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull aissatoudrame/gestion-enseignants:v01
            cd /docker-file-l3l2i
            docker-compose down --remove-orphans
            docker system prune -af
            docker-compose up -d

#
#      - name: Déployer l'application sur le VPS
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.SSH_PORT }}
#          script: |
#            docker pull aissatoudrame/frontend-user-app-react:latest
#            cd /docker-compose-files
#          #docker-compose -f docker-compose-frontend.yml up -d






